# Generated by Django 6.0 on 2025-12-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['ordem'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='nivel',
        ),
        migrations.AddField(
            model_name='skill',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
