# Generated by Django 5.2.9 on 2025-12-13 18:51

import django.core.validators
import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_skill_options_remove_skill_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.skill', verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp']), portfolio.models.validate_image_size]),
        ),
        migrations.CreateModel(
            name='ProjetoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif']), portfolio.models.validate_image_size])),
                ('ordem', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens do Projeto',
                'ordering': ['ordem'],
            },
        ),
    ]
